import {
  faLocationDot,
  faMagnifyingGlass,
  faCheck,
  faSpinner,
  faImages,
  faCircleXmark,
  faChevronLeft,
  faHouse,
  faXmark,
  faMap,
  faHouseCircleCheck,
  faBuilding,
  faSquare,
  faArrowRightToBracket,
  faArrowRightFromBracket,
} from '@fortawesome/free-solid-svg-icons';

export default [
  faLocationDot,
  faMagnifyingGlass,
  faCheck,
  faSpinner,
  faImages,
  faCircleXmark,
  faChevronLeft,
  faHouse,
  faXmark,
  faMap,
  faHouseCircleCheck,
  faBuilding,
  faSquare,
  faArrowRightToBracket,
  faArrowRightFromBracket,
];
